Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from rdflib import Graph

# Create a Graph
g = Graph()

# Parse in an RDF file hosted on the Internet
g.parse("https://models.open223.info/guideline36-2021-4.1.ttl", format="ttl")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mHTTPError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 7[0m
[1;32m      4[0m g [38;5;241m=[39m Graph()
[1;32m      6[0m [38;5;66;03m# Parse in an RDF file hosted on the Internet[39;00m
[0;32m----> 7[0m [43mg[49m[38;5;241;43m.[39;49m[43mparse[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mhttps://models.open223.info/guideline36-2021-4.1.ttl[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[38;5;28;43mformat[39;49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mttl[39;49m[38;5;124;43m"[39;49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/rdflib/graph.py:1467[0m, in [0;36mGraph.parse[0;34m(self, source, publicID, format, location, file, data, **args)[0m
[1;32m   1372[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21mparse[39m(
[1;32m   1373[0m     [38;5;28mself[39m,
[1;32m   1374[0m     source: Optional[
[0;32m   (...)[0m
[1;32m   1382[0m     [38;5;241m*[39m[38;5;241m*[39margs: Any,
[1;32m   1383[0m ) [38;5;241m-[39m[38;5;241m>[39m Graph:
[1;32m   1384[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m   1385[0m [38;5;124;03m    Parse an RDF source adding the resulting triples to the Graph.[39;00m
[1;32m   1386[0m 
[0;32m   (...)[0m
[1;32m   1464[0m 
[1;32m   1465[0m [38;5;124;03m    """[39;00m
[0;32m-> 1467[0m     source [38;5;241m=[39m [43mcreate_input_source[49m[43m([49m
[1;32m   1468[0m [43m        [49m[43msource[49m[38;5;241;43m=[39;49m[43msource[49m[43m,[49m
[1;32m   1469[0m [43m        [49m[43mpublicID[49m[38;5;241;43m=[39;49m[43mpublicID[49m[43m,[49m
[1;32m   1470[0m [43m        [49m[43mlocation[49m[38;5;241;43m=[39;49m[43mlocation[49m[43m,[49m
[1;32m   1471[0m [43m        [49m[43mfile[49m[38;5;241;43m=[39;49m[43mfile[49m[43m,[49m
[1;32m   1472[0m [43m        [49m[43mdata[49m[38;5;241;43m=[39;49m[43mdata[49m[43m,[49m
[1;32m   1473[0m [43m        [49m[38;5;28;43mformat[39;49m[38;5;241;43m=[39;49m[38;5;28;43mformat[39;49m[43m,[49m
[1;32m   1474[0m [43m    [49m[43m)[49m
[1;32m   1475[0m     [38;5;28;01mif[39;00m [38;5;28mformat[39m [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m   1476[0m         [38;5;28mformat[39m [38;5;241m=[39m source[38;5;241m.[39mcontent_type

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/rdflib/parser.py:735[0m, in [0;36mcreate_input_source[0;34m(source, publicID, location, file, data, format)[0m
[1;32m    728[0m         [38;5;28;01massert[39;00m data [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m
[1;32m    729[0m         [38;5;28;01massert[39;00m source [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m
[1;32m    730[0m     (
[1;32m    731[0m         absolute_location,
[1;32m    732[0m         auto_close,
[1;32m    733[0m         file,
[1;32m    734[0m         input_source,
[0;32m--> 735[0m     ) [38;5;241m=[39m [43m_create_input_source_from_location[49m[43m([49m
[1;32m    736[0m [43m        [49m[43mfile[49m[38;5;241;43m=[39;49m[43mfile[49m[43m,[49m
[1;32m    737[0m [43m        [49m[38;5;28;43mformat[39;49m[38;5;241;43m=[39;49m[38;5;28;43mformat[39;49m[43m,[49m
[1;32m    738[0m [43m        [49m[43minput_source[49m[38;5;241;43m=[39;49m[43minput_source[49m[43m,[49m
[1;32m    739[0m [43m        [49m[43mlocation[49m[38;5;241;43m=[39;49m[43mlocation[49m[43m,[49m
[1;32m    740[0m [43m    [49m[43m)[49m
[1;32m    742[0m [38;5;28;01mif[39;00m file [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    743[0m     [38;5;28;01mif[39;00m TYPE_CHECKING:

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/rdflib/parser.py:797[0m, in [0;36m_create_input_source_from_location[0;34m(file, format, input_source, location)[0m
[1;32m    795[0m     file [38;5;241m=[39m [38;5;28mopen[39m(filename, [38;5;124m"[39m[38;5;124mrb[39m[38;5;124m"[39m)
[1;32m    796[0m [38;5;28;01melse[39;00m:
[0;32m--> 797[0m     input_source [38;5;241m=[39m [43mURLInputSource[49m[43m([49m[43mabsolute_location[49m[43m,[49m[43m [49m[38;5;28;43mformat[39;49m[43m)[49m
[1;32m    799[0m auto_close [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m    800[0m [38;5;66;03m# publicID = publicID or absolute_location  # Further to fix[39;00m
[1;32m    801[0m [38;5;66;03m# for issue 130[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/rdflib/parser.py:594[0m, in [0;36mURLInputSource.__init__[0;34m(self, system_id, format)[0m
[1;32m    590[0m     myheaders[[38;5;124m"[39m[38;5;124mAccept[39m[38;5;124m"[39m] [38;5;241m=[39m [38;5;124m"[39m[38;5;124m, [39m[38;5;124m"[39m[38;5;241m.[39mjoin(acc)
[1;32m    592[0m req [38;5;241m=[39m Request(system_id, [38;5;28;01mNone[39;00m, myheaders)  [38;5;66;03m# type: ignore[arg-type][39;00m
[0;32m--> 594[0m response: addinfourl [38;5;241m=[39m [43m_urlopen[49m[43m([49m[43mreq[49m[43m)[49m
[1;32m    595[0m [38;5;28mself[39m[38;5;241m.[39murl [38;5;241m=[39m response[38;5;241m.[39mgeturl()  [38;5;66;03m# in case redirections took place[39;00m
[1;32m    596[0m [38;5;28mself[39m[38;5;241m.[39mlinks [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mget_links(response)

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/rdflib/_networking.py:106[0m, in [0;36m_urlopen[0;34m(request)[0m
[1;32m     95[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m     96[0m [38;5;124;03mThis is a shim for `urlopen` that handles HTTP redirects with status code[39;00m
[1;32m     97[0m [38;5;124;03m308 (Permanent Redirect).[39;00m
[0;32m   (...)[0m
[1;32m    103[0m [38;5;124;03m:return: The response to the request.[39;00m
[1;32m    104[0m [38;5;124;03m"""[39;00m
[1;32m    105[0m [38;5;28;01mtry[39;00m:
[0;32m--> 106[0m     [38;5;28;01mreturn[39;00m [43murlopen[49m[43m([49m[43mrequest[49m[43m)[49m
[1;32m    107[0m [38;5;28;01mexcept[39;00m HTTPError [38;5;28;01mas[39;00m error:
[1;32m    108[0m     [38;5;28;01mif[39;00m error[38;5;241m.[39mcode [38;5;241m==[39m [38;5;241m308[39m [38;5;129;01mand[39;00m sys[38;5;241m.[39mversion_info [38;5;241m<[39m ([38;5;241m3[39m, [38;5;241m11[39m):
[1;32m    109[0m         [38;5;66;03m# HTTP response code 308 (Permanent Redirect) is not supported by python[39;00m
[1;32m    110[0m         [38;5;66;03m# versions older than 3.11. See <https://bugs.python.org/issue40321> and[39;00m
[1;32m    111[0m         [38;5;66;03m# <https://github.com/python/cpython/issues/84501> for more details.[39;00m
[1;32m    112[0m         [38;5;66;03m# This custom error handling should be removed once all supported[39;00m
[1;32m    113[0m         [38;5;66;03m# versions of Python handles 308.[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/urllib/request.py:216[0m, in [0;36murlopen[0;34m(url, data, timeout, cafile, capath, cadefault, context)[0m
[1;32m    214[0m [38;5;28;01melse[39;00m:
[1;32m    215[0m     opener [38;5;241m=[39m _opener
[0;32m--> 216[0m [38;5;28;01mreturn[39;00m [43mopener[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43murl[49m[43m,[49m[43m [49m[43mdata[49m[43m,[49m[43m [49m[43mtimeout[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/urllib/request.py:525[0m, in [0;36mOpenerDirector.open[0;34m(self, fullurl, data, timeout)[0m
[1;32m    523[0m [38;5;28;01mfor[39;00m processor [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39mprocess_response[38;5;241m.[39mget(protocol, []):
[1;32m    524[0m     meth [38;5;241m=[39m [38;5;28mgetattr[39m(processor, meth_name)
[0;32m--> 525[0m     response [38;5;241m=[39m [43mmeth[49m[43m([49m[43mreq[49m[43m,[49m[43m [49m[43mresponse[49m[43m)[49m
[1;32m    527[0m [38;5;28;01mreturn[39;00m response

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/urllib/request.py:634[0m, in [0;36mHTTPErrorProcessor.http_response[0;34m(self, request, response)[0m
[1;32m    631[0m [38;5;66;03m# According to RFC 2616, "2xx" code indicates that the client's[39;00m
[1;32m    632[0m [38;5;66;03m# request was successfully received, understood, and accepted.[39;00m
[1;32m    633[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m ([38;5;241m200[39m [38;5;241m<[39m[38;5;241m=[39m code [38;5;241m<[39m [38;5;241m300[39m):
[0;32m--> 634[0m     response [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mparent[49m[38;5;241;43m.[39;49m[43merror[49m[43m([49m
[1;32m    635[0m [43m        [49m[38;5;124;43m'[39;49m[38;5;124;43mhttp[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mrequest[49m[43m,[49m[43m [49m[43mresponse[49m[43m,[49m[43m [49m[43mcode[49m[43m,[49m[43m [49m[43mmsg[49m[43m,[49m[43m [49m[43mhdrs[49m[43m)[49m
[1;32m    637[0m [38;5;28;01mreturn[39;00m response

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/urllib/request.py:563[0m, in [0;36mOpenerDirector.error[0;34m(self, proto, *args)[0m
[1;32m    561[0m [38;5;28;01mif[39;00m http_err:
[1;32m    562[0m     args [38;5;241m=[39m ([38;5;28mdict[39m, [38;5;124m'[39m[38;5;124mdefault[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mhttp_error_default[39m[38;5;124m'[39m) [38;5;241m+[39m orig_args
[0;32m--> 563[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_call_chain[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/urllib/request.py:496[0m, in [0;36mOpenerDirector._call_chain[0;34m(self, chain, kind, meth_name, *args)[0m
[1;32m    494[0m [38;5;28;01mfor[39;00m handler [38;5;129;01min[39;00m handlers:
[1;32m    495[0m     func [38;5;241m=[39m [38;5;28mgetattr[39m(handler, meth_name)
[0;32m--> 496[0m     result [38;5;241m=[39m [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m)[49m
[1;32m    497[0m     [38;5;28;01mif[39;00m result [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    498[0m         [38;5;28;01mreturn[39;00m result

File [0;32m/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/urllib/request.py:643[0m, in [0;36mHTTPDefaultErrorHandler.http_error_default[0;34m(self, req, fp, code, msg, hdrs)[0m
[1;32m    642[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21mhttp_error_default[39m([38;5;28mself[39m, req, fp, code, msg, hdrs):
[0;32m--> 643[0m     [38;5;28;01mraise[39;00m HTTPError(req[38;5;241m.[39mfull_url, code, msg, hdrs, fp)

[0;31mHTTPError[0m: HTTP Error 404: Not Found

